[theme]
# Paleta UVM Querétaro: blanco + rojo
primaryColor = "#E30613"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#FDF3F3"
textColor = "#1F1F1F"
font = "sans serif"

[server]
runOnSave = true

[browser]
gatherUsageStats = false